service: cursive-ai

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  memory: 1024
  timeout: 30

functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  customDomain:
    domainName: cursive.ai
    hostedZoneId: ZY9AETNBV8YF6
    endpointType: regional # otherwise, certificate needs to be in us-east-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
